[release/0.24] cherrypicks for windows failing jobs (#9230)
Co-authored-by: Nicolas Hug <nicolashug@meta.com>

diff --git a/.github/workflows/build-cmake.yml b/.github/workflows/build-cmake.yml
--- a/.github/workflows/build-cmake.yml
+++ b/.github/workflows/build-cmake.yml
@@ -58,30 +58,30 @@ jobs:
 
         ${CONDA_RUN} ./.github/scripts/cmake.sh
 
-  windows:
-    strategy:
-      matrix:
-        include:
-          - runner: windows.4xlarge
-            gpu-arch-type: cpu
-          - runner: windows.g5.4xlarge.nvidia.gpu
-            gpu-arch-type: cuda
-            gpu-arch-version: "12.6"
-      fail-fast: false
-    uses: pytorch/test-infra/.github/workflows/windows_job.yml@release/2.9
-    with:
-      repository: pytorch/vision
-      runner: ${{ matrix.runner }}
-      gpu-arch-type: ${{ matrix.gpu-arch-type }}
-      gpu-arch-version: ${{ matrix.gpu-arch-version }}
-      test-infra-ref: release/2.9
-      script: |
-        set -euo pipefail
+  # windows:
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - runner: windows.4xlarge
+  #           gpu-arch-type: cpu
+  #         - runner: windows.g5.4xlarge.nvidia.gpu
+  #           gpu-arch-type: cuda
+  #           gpu-arch-version: "12.6"
+  #     fail-fast: false
+  #   uses: pytorch/test-infra/.github/workflows/windows_job.yml@release/2.9
+  #   with:
+  #     repository: pytorch/vision
+  #     runner: ${{ matrix.runner }}
+  #     gpu-arch-type: ${{ matrix.gpu-arch-type }}
+  #     gpu-arch-version: ${{ matrix.gpu-arch-version }}
+  #     test-infra-ref: release/2.9
+  #     script: |
+  #       set -euo pipefail
 
-        export PYTHON_VERSION=3.9
-        export VC_YEAR=2022
-        export VSDEVCMD_ARGS=""
-        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
-        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
+  #       export PYTHON_VERSION=3.9
+  #       export VC_YEAR=2022
+  #       export VSDEVCMD_ARGS=""
+  #       export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
+  #       export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
 
-        ./.github/scripts/cmake.sh
+  #       ./.github/scripts/cmake.sh
