disable windows for now

diff --git a/.github/workflows/build-cmake.yml b/.github/workflows/build-cmake.yml
--- a/.github/workflows/build-cmake.yml
+++ b/.github/workflows/build-cmake.yml
@@ -55,27 +55,27 @@ jobs:
 
         ./.github/scripts/cmake.sh
 
-  windows:
-    strategy:
-      matrix:
-        include:
-          - runner: windows.4xlarge
-            gpu-arch-type: cpu
-          - runner: windows.g5.4xlarge.nvidia.gpu
-            gpu-arch-type: cuda
-            gpu-arch-version: "11.7"
-      fail-fast: false
-    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
-    with:
-      repository: pytorch/vision
-      runner: ${{ matrix.runner }}
-      gpu-arch-type: ${{ matrix.gpu-arch-type }}
-      gpu-arch-version: ${{ matrix.gpu-arch-version }}
-      script: |
-        set -euo pipefail
-
-        export PYTHON_VERSION=3.8
-        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
-        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
-
-        ./.github/scripts/cmake.sh
+#  windows:
+#    strategy:
+#      matrix:
+#        include:
+#          - runner: windows.4xlarge
+#            gpu-arch-type: cpu
+#          - runner: windows.g5.4xlarge.nvidia.gpu
+#            gpu-arch-type: cuda
+#            gpu-arch-version: "11.7"
+#      fail-fast: false
+#    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
+#    with:
+#      repository: pytorch/vision
+#      runner: ${{ matrix.runner }}
+#      gpu-arch-type: ${{ matrix.gpu-arch-type }}
+#      gpu-arch-version: ${{ matrix.gpu-arch-version }}
+#      script: |
+#        set -euo pipefail
+#
+#        export PYTHON_VERSION=3.8
+#        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
+#        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
+#
+#        ./.github/scripts/cmake.sh
