refactor env var handling

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -69,34 +69,35 @@ jobs:
       script: |
         set -euo pipefail
         
-        TARGET=${{ github.ref_name }}
-        if [[ ${{ github.ref_type }} == 'branch' ]]; then
-          echo "Branch: ${TARGET}"
-        else
-          case "${TARGET}" in
+        REF_TYPE=${{ github.ref_type }}
+        REF_NAME=${{ github.ref_name }}
+
+        if [[ "${REF_TYPE}" == branch ]]; then
+          TARGET_FOLDER="${REF_NAME}"
+        elif [[ "${REF_TYPE}" == tag ]]; then
+          case "${REF_NAME}" in
             *-rc*)
-              echo "Aborting upload since this is an RC tag: ${TARGET}"
+              echo "Aborting upload since this is an RC tag: ${REF_NAME}"
               exit 0
               ;;
             *)
-              echo "Tag: ${TARGET}"
               # Strip the leading "v" as well as the trailing patch version. For example:
               # 'v0.15.2' -> '0.15'
-              TARGET=$(echo "${TARGET}" | sed 's/v\([0-9]\+\)\.\([0-9]\+\)\.[0-9]\+/\1.\2/')
-              echo "Target Folder: ${TARGET}"
+              TARGET_FOLDER=$(echo "${REF_NAME}" | sed 's/v\([0-9]\+\)\.\([0-9]\+\)\.[0-9]\+/\1.\2/')
               ;;
           esac
         fi
+        echo "Target Folder: ${TARGET_FOLDER}"
 
-        mkdir -p "${TARGET}"
-        rm -rf "${TARGET}"/*
-        mv "${RUNNER_ARTIFACT_DIR}"/html/* "${TARGET}"
-        git add "${TARGET}" || true
+        mkdir -p "${TARGET_FOLDER}"
+        rm -rf "${TARGET_FOLDER}"/*
+        mv "${RUNNER_ARTIFACT_DIR}"/html/* "${TARGET_FOLDER}"
+        git add "${TARGET_FOLDER}" || true
         
-        if [[ "${TARGET}" == main ]]; then
+        if [[ "${TARGET_FOLDER}" == main ]]; then
           mkdir -p _static
           rm -rf _static/*
-          cp -r "${TARGET}"/_static/* _static
+          cp -r "${TARGET_FOLDER}"/_static/* _static
           git add _static || true
         fi
         
