Run windows jobs

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -44,7 +44,33 @@ jobs:
 
 #         ./.github/scripts/unittest.sh
 
-  unittests-macos:
+#   unittests-macos:
+#     strategy:
+#       matrix:
+#         python-version:
+#         #   - "3.8"
+#         #   - "3.9"
+#         #   - "3.10"
+#           - "3.11"
+#         #   - "3.12"
+#         runner: ["macos-m1-stable"]
+#       fail-fast: false
+#     uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
+#     with:
+#       repository: pytorch/vision
+#       timeout: 240
+#       runner: ${{ matrix.runner }}
+#       test-infra-ref: main
+#       script: |
+#         set -euo pipefail
+
+#         export PYTHON_VERSION=${{ matrix.python-version }}
+#         export GPU_ARCH_TYPE=cpu
+#         export GPU_ARCH_VERSION=''
+
+#         ${CONDA_RUN} ./.github/scripts/unittest.sh
+
+  unittests-windows:
     strategy:
       matrix:
         python-version:
@@ -53,58 +79,32 @@ jobs:
         #   - "3.10"
           - "3.11"
         #   - "3.12"
-        runner: ["macos-m1-stable"]
+        runner: ["windows.4xlarge"]
+        gpu-arch-type: ["cpu"]
+        include:
+          - python-version: "3.8"
+            runner: windows.g5.4xlarge.nvidia.gpu
+            gpu-arch-type: cuda
+            gpu-arch-version: "11.8"
       fail-fast: false
-    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
+    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
     with:
       repository: pytorch/vision
-      timeout: 240
       runner: ${{ matrix.runner }}
+      gpu-arch-type: ${{ matrix.gpu-arch-type }}
+      gpu-arch-version: ${{ matrix.gpu-arch-version }}
+      timeout: 120
       test-infra-ref: main
       script: |
-        set -euo pipefail
+        set -euxo pipefail
 
         export PYTHON_VERSION=${{ matrix.python-version }}
-        export GPU_ARCH_TYPE=cpu
-        export GPU_ARCH_VERSION=''
+        export VC_YEAR=2019
+        export VSDEVCMD_ARGS=""
+        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
+        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
 
-        ${CONDA_RUN} ./.github/scripts/unittest.sh
-
-#   unittests-windows:
-#     strategy:
-#       matrix:
-#         python-version:
-#           - "3.8"
-#           - "3.9"
-#           - "3.10"
-#           - "3.11"
-#           - "3.12"
-#         runner: ["windows.4xlarge"]
-#         gpu-arch-type: ["cpu"]
-#         include:
-#           - python-version: "3.8"
-#             runner: windows.g5.4xlarge.nvidia.gpu
-#             gpu-arch-type: cuda
-#             gpu-arch-version: "11.8"
-#       fail-fast: false
-#     uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
-#     with:
-#       repository: pytorch/vision
-#       runner: ${{ matrix.runner }}
-#       gpu-arch-type: ${{ matrix.gpu-arch-type }}
-#       gpu-arch-version: ${{ matrix.gpu-arch-version }}
-#       timeout: 120
-#       test-infra-ref: main
-#       script: |
-#         set -euxo pipefail
-
-#         export PYTHON_VERSION=${{ matrix.python-version }}
-#         export VC_YEAR=2019
-#         export VSDEVCMD_ARGS=""
-#         export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
-#         export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
-
-#         ./.github/scripts/unittest.sh
+        ./.github/scripts/unittest.sh
 
 #   onnx:
 #     uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
