Put back stuff

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -68,40 +68,40 @@ jobs:
 
   #       ${CONDA_RUN} ./.github/scripts/unittest.sh
 
-  unittests-windows:
-    strategy:
-      matrix:
-        python-version:
-          - "3.9"
-          # - "3.10"
-          # - "3.11"
-          # - "3.12"
-        runner: ["windows.4xlarge.nonephemeral"]
-        gpu-arch-type: ["cpu"]
-        # include:
-        #   - python-version: "3.9"
-        #     runner: windows.g5.4xlarge.nvidia.gpu
-        #     gpu-arch-type: cuda
-        #     gpu-arch-version: "11.8"
-      fail-fast: false
-    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
-    with:
-      repository: pytorch/vision
-      runner: ${{ matrix.runner }}
-      gpu-arch-type: ${{ matrix.gpu-arch-type }}
-      gpu-arch-version: ${{ matrix.gpu-arch-version }}
-      timeout: 120
-      test-infra-ref: main
-      script: |
-        set -euxo pipefail
+  # unittests-windows:
+  #   strategy:
+  #     matrix:
+  #       python-version:
+  #         - "3.9"
+  #         # - "3.10"
+  #         # - "3.11"
+  #         # - "3.12"
+  #       runner: ["windows.4xlarge.nonephemeral"]
+  #       gpu-arch-type: ["cpu"]
+  #       # include:
+  #       #   - python-version: "3.9"
+  #       #     runner: windows.g5.4xlarge.nvidia.gpu
+  #       #     gpu-arch-type: cuda
+  #       #     gpu-arch-version: "11.8"
+  #     fail-fast: false
+  #   uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
+  #   with:
+  #     repository: pytorch/vision
+  #     runner: ${{ matrix.runner }}
+  #     gpu-arch-type: ${{ matrix.gpu-arch-type }}
+  #     gpu-arch-version: ${{ matrix.gpu-arch-version }}
+  #     timeout: 120
+  #     test-infra-ref: main
+  #     script: |
+  #       set -euxo pipefail
 
-        export PYTHON_VERSION=${{ matrix.python-version }}
-        export VC_YEAR=2019
-        export VSDEVCMD_ARGS=""
-        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
-        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
+  #       export PYTHON_VERSION=${{ matrix.python-version }}
+  #       export VC_YEAR=2019
+  #       export VSDEVCMD_ARGS=""
+  #       export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
+  #       export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
 
-        ./.github/scripts/unittest.sh
+  #       ./.github/scripts/unittest.sh
 
   # onnx:
   #   uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
